"""Add public_id to clients

Revision ID: 137d3397e97f
Revises: 7ef8d545d31d
Create Date: 2025-10-19 19:56:55.571714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137d3397e97f'
down_revision: Union[str, Sequence[str], None] = '7ef8d545d31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('public_id', sa.String(length=12), nullable=False))
    op.create_unique_constraint(None, 'clients', ['public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'public_id')
    # ### end Alembic commands ###
