"""rm session.mode, add session Tags

Revision ID: 320a6157356b
Revises: bd56b03219fe
Create Date: 2026-03-23 16:28:00.410607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '320a6157356b'
down_revision: Union[str, Sequence[str], None] = 'bd56b03219fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False, server_default='#6B7280'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainer_id', 'name', name='uq_tag_name_per_trainer')
    )
    op.create_index(op.f('ix_tags_trainer_id'), 'tags', ['trainer_id'], unique=False)
    op.create_table('session_tags',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'tag_id')
    )
    op.drop_column('sessions', 'mode')
    sa.Enum(name='session_format').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('online', 'offline', name='session_format').create(op.get_bind())
    op.add_column('sessions', sa.Column('mode', postgresql.ENUM('online', 'offline', name='session_format'), server_default=sa.text("'offline'::session_format"), autoincrement=False, nullable=False))
    op.drop_table('session_tags')
    op.drop_index(op.f('ix_tags_trainer_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
