"""init

Revision ID: af95114c49c3
Revises: 
Create Date: 2025-12-29 20:58:43.478449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af95114c49c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default='Europe/Kyiv', nullable=True),
    sa.Column('currency', sa.Enum('UAH', 'USD', 'EUR', name='currency_enum'), server_default='UAH', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=6), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'pause', name='status_enum'), server_default='active', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('price >= 0', name='ck_client_price_nonnegative'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('trainer_id', 'name', name='uq_client_name_per_trainer')
    )
    op.create_index(op.f('ix_clients_trainer_id'), 'clients', ['trainer_id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainer_id', 'name', name='uq_exercise_name_per_trainer')
    )
    op.create_index(op.f('ix_exercises_trainer_id'), 'exercises', ['trainer_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=8), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('start_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), server_default='60', nullable=False),
    sa.Column('mode', sa.Enum('online', 'offline', name='session_format'), server_default='offline', nullable=False),
    sa.Column('status', sa.Enum('planned', 'done', 'cancelled', 'no_show', name='session_status'), server_default='planned', nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('duration_min > 0', name='ck_session_duration_positive'),
    sa.CheckConstraint('price >= 0', name='ck_session_price_nonnegative'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_sessions_client_id'), 'sessions', ['client_id'], unique=False)
    op.create_index(op.f('ix_sessions_start_dt'), 'sessions', ['start_dt'], unique=False)
    op.create_table('session_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('reps > 0', name='ck_session_exercise_reps_positive'),
    sa.CheckConstraint('sets > 0', name='ck_session_exercise_sets_positive'),
    sa.CheckConstraint('weight >= 0', name='ck_session_exercise_weight_nonnegative'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_se_client_exercise', 'session_exercises', ['client_id', 'exercise_id'], unique=False)
    op.create_index(op.f('ix_session_exercises_client_id'), 'session_exercises', ['client_id'], unique=False)
    op.create_index(op.f('ix_session_exercises_exercise_id'), 'session_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_session_exercises_session_id'), 'session_exercises', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_exercises_session_id'), table_name='session_exercises')
    op.drop_index(op.f('ix_session_exercises_exercise_id'), table_name='session_exercises')
    op.drop_index(op.f('ix_session_exercises_client_id'), table_name='session_exercises')
    op.drop_index('ix_se_client_exercise', table_name='session_exercises')
    op.drop_table('session_exercises')
    op.drop_index(op.f('ix_sessions_start_dt'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_client_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_exercises_trainer_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_clients_trainer_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('trainers')
    # ### end Alembic commands ###
